config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :opportunities
  resources :post_tests
  resources :entries
  resources :contacts
  get 'welcome/index'

  root 'welcome#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]


  def list

  end


  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
    #@contacts = Salesforce::Contact.all
    #@contact = SELECT * FROM salesforce.contact WHERE sfid IS NULL AND _hc_lastop='FAILED';
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:name, :emp_id, :SFID, :Last_Change, :Modified_At, :Message)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :emp_id %><br>
    <%= f.number_field :emp_id %>
  </div>
  <div class="field">
    <%= f.label :SFID %><br>
    <%= f.text_field :SFID %>
  </div>
  <div class="field">
    <%= f.label :Last_Change %><br>
    <%= f.text_field :Last_Change %>
  </div>
  <div class="field">
    <%= f.label :Modified_At %><br>
    <%= f.text_field :Modified_At %>
  </div>
  <div class="field">
    <%= f.label :Message %><br>
    <%= f.text_field :Message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<style>
table {
    border-collapse: separate;
    border-spacing: 15px 10px;
  }

  p.big{
    font-weight:bold;
    font-size:16px;
}

</style>

<p id="notice"><%= notice %></p>

<h1>Data Entries</h1>


<h3>Existing Contacts</h3>
<p>
  <% if @contacts.blank? %>
    <p> There are no contacts in the system </p>
  <% else %>
    <ul id="contacts"> <% @contacts.each do |c| %>
        <li>
          <%= c.name -%>
      </li>
  <% end %>
</ul>  <% end %>
</p>




<table>
  <thead>
    <tr>
      <th><p class='big'>Name</p></th>
      <th><p class='big'>ID</p></th>
      <th><p class='big'>SFID </p></th>
      <th><p class='big'>Last change</p></th>
      <th><p class='big'>Modified At</p></th>
      <th><p class='big'>Message</p></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
        <td><%= entry.emp_id %></td>
        <td><%= entry.SFID %></td>
        <td><%= entry.Last_Change %></td>
        <td><%= entry.Modified_At %></td>
        <td><%= entry.Message %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br><br><br><br><br>
<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entry.name %>
</p>

<p>
  <strong>Emp:</strong>
  <%= @entry.emp_id %>
</p>

<p>
  <strong>Sfid:</strong>
  <%= @entry.SFID %>
</p>

<p>
  <strong>Last change:</strong>
  <%= @entry.Last_Change %>
</p>

<p>
  <strong>Modified at:</strong>
  <%= @entry.Modified_At %>
</p>

<p>
  <strong>Message:</strong>
  <%= @entry.Message %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>