config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :opportunities
  resources :post_tests
  resources :entries
  resources :contacts
  get 'welcome/index'

  root 'welcome#index'

end

app/models/opportunity.rb
class Opportunity < SalesforceModel
  #self.table_name = ENV['HEROKUCONNECT_SCHEMA'] + '.contact'
  self.table_name = 'opportunity'
  belongs_to :account, :primary_key => 'sfid', :foreign_key => 'accountid'

  #attr_protected :createddate, :systemmodstamp, :lastmodifieddate
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  before_action :set_opportunity, only: [:show, :edit, :update, :destroy]

  def opportunities
    #@page = (params[:page] || 1).to_i
    @opportunities = Opportunity.find :all
    #@a_contact = Contact.find :all
    #@contacts = Contact.find_by_AccountID(params[:id])
    #@contacts = Contact.order("lastname").offset(@page*20).limit(20).all()
    render :layout => false
  end
  
  # GET /opportunities
  # GET /opportunities.json
  def index
    @opportunities = Opportunity.all
  end

  # GET /opportunities/1
  # GET /opportunities/1.json
  def show
  end

  # GET /opportunities/new
  def new
    @opportunity = Opportunity.new
  end

  # GET /opportunities/1/edit
  def edit
  end

  # POST /opportunities
  # POST /opportunities.json
  def create
    @opportunity = Opportunity.new(opportunity_params)

    respond_to do |format|
      if @opportunity.save
        format.html { redirect_to @opportunity, notice: 'Opportunity was successfully created.' }
        format.json { render :show, status: :created, location: @opportunity }
      else
        format.html { render :new }
        format.json { render json: @opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opportunities/1
  # PATCH/PUT /opportunities/1.json
  def update
    respond_to do |format|
      if @opportunity.update(opportunity_params)
        format.html { redirect_to @opportunity, notice: 'Opportunity was successfully updated.' }
        format.json { render :show, status: :ok, location: @opportunity }
      else
        format.html { render :edit }
        format.json { render json: @opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opportunities/1
  # DELETE /opportunities/1.json
  def destroy
    @opportunity.destroy
    respond_to do |format|
      format.html { redirect_to opportunities_url, notice: 'Opportunity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opportunity
      @opportunity = Opportunity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opportunity_params
      params.require(:opportunity).permit(:proposalduedate__c, :systemmodstamp, :accountid, :currencyisocode, :stagename, :isdeleted, :closedate, :opportunity_md_d__c, :leadsource, :_hc_lastop, :primary_key_buyer__c, :probability, :amount, :_hc_err, :type, :sfid, :natureofwork__c, :pursuitteam__c, :createddate, :name)
    end
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/views/opportunities/_form.html.erb
<%= form_for(@opportunity) do |f| %>
  <% if @opportunity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opportunity.errors.count, "error") %> prohibited this opportunity from being saved:</h2>

      <ul>
      <% @opportunity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proposalduedate__c %><br>
    <%= f.date_select :proposalduedate__c %>
  </div>
  <div class="field">
    <%= f.label :systemmodstamp %><br>
    <%= f.datetime_select :systemmodstamp %>
  </div>
  <div class="field">
    <%= f.label :accountid %><br>
    <%= f.text_field :accountid %>
  </div>
  <div class="field">
    <%= f.label :currencyisocode %><br>
    <%= f.text_field :currencyisocode %>
  </div>
  <div class="field">
    <%= f.label :stagename %><br>
    <%= f.text_field :stagename %>
  </div>
  <div class="field">
    <%= f.label :isdeleted %><br>
    <%= f.check_box :isdeleted %>
  </div>
  <div class="field">
    <%= f.label :closedate %><br>
    <%= f.date_select :closedate %>
  </div>
  <div class="field">
    <%= f.label :opportunity_md_d__c %><br>
    <%= f.text_field :opportunity_md_d__c %>
  </div>
  <div class="field">
    <%= f.label :leadsource %><br>
    <%= f.text_field :leadsource %>
  </div>
  <div class="field">
    <%= f.label :_hc_lastop %><br>
    <%= f.text_field :_hc_lastop %>
  </div>
  <div class="field">
    <%= f.label :primary_key_buyer__c %><br>
    <%= f.text_field :primary_key_buyer__c %>
  </div>
  <div class="field">
    <%= f.label :probability %><br>
    <%= f.text_field :probability %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :_hc_err %><br>
    <%= f.text_area :_hc_err %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :sfid %><br>
    <%= f.text_field :sfid %>
  </div>
  <div class="field">
    <%= f.label :natureofwork__c %><br>
    <%= f.text_field :natureofwork__c %>
  </div>
  <div class="field">
    <%= f.label :pursuitteam__c %><br>
    <%= f.text_field :pursuitteam__c %>
  </div>
  <div class="field">
    <%= f.label :createddate %><br>
    <%= f.datetime_select :createddate %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opportunities/edit.html.erb
<h1>Editing Opportunity</h1>

<%= render 'form' %>

<%= link_to 'Show', @opportunity %> |
<%= link_to 'Back', opportunities_path %>

app/views/opportunities/index.html.erb
<style>
  table{
      border-collapse: separate;
    border-spacing: 10px 5px;
  }
</style>

<p id="notice"><%= notice %></p>

<h1>Opportunities</h1>

<table>
  <thead>
    <tr>

      <th>Name</th>
      <th>Lead Source</th>
      <th>Amount</th>
      <th>Type</th>
      <th>Stage Name</th>
      <th>Pursuit Team</th>
      <th>Close Date</th>
      <th>Proposal Due Date</th>
      <th>Probability</th>
      <th>Nature of Work</th>
    </tr>
  </thead>

  <tbody>
    <% @opportunities.each do |opportunity| %>
      <tr>
        <td><%= opportunity.name %></td>
        <td><%= opportunity.leadsource %></td>
        <td><%= opportunity.amount %></td>
        <td><%= opportunity.type %></td>
        <td><%= opportunity.stagename %></td>
        <td><%= opportunity.pursuitteam__c %></td>
        <td><%= opportunity.closedate %></td>
        <td><%= opportunity.proposalduedate__c %></td>
        <td><%= opportunity.probability %></td>
        <td><%= opportunity.natureofwork__c %></td>

        <td><%= link_to 'Show', opportunity %></td>
        <td><%= link_to 'Edit', edit_opportunity_path(opportunity) %></td>
        <td><%= link_to 'Delete', opportunity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opportunity', new_opportunity_path %>

app/views/opportunities/new.html.erb
<h1>New Opportunity</h1>

<%= render 'form' %>

<%= link_to 'Back', opportunities_path %>

app/views/opportunities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proposalduedate  c:</strong>
  <%= @opportunity.proposalduedate__c %>
</p>

<p>
  <strong>Systemmodstamp:</strong>
  <%= @opportunity.systemmodstamp %>
</p>

<p>
  <strong>Accountid:</strong>
  <%= @opportunity.accountid %>
</p>

<p>
  <strong>Currencyisocode:</strong>
  <%= @opportunity.currencyisocode %>
</p>

<p>
  <strong>Stagename:</strong>
  <%= @opportunity.stagename %>
</p>

<p>
  <strong>Isdeleted:</strong>
  <%= @opportunity.isdeleted %>
</p>

<p>
  <strong>Closedate:</strong>
  <%= @opportunity.closedate %>
</p>

<p>
  <strong>Opportunity md d  c:</strong>
  <%= @opportunity.opportunity_md_d__c %>
</p>

<p>
  <strong>Leadsource:</strong>
  <%= @opportunity.leadsource %>
</p>

<p>
  <strong>Hc lastop:</strong>
  <%= @opportunity._hc_lastop %>
</p>

<p>
  <strong>Primary key buyer  c:</strong>
  <%= @opportunity.primary_key_buyer__c %>
</p>

<p>
  <strong>Probability:</strong>
  <%= @opportunity.probability %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @opportunity.amount %>
</p>

<p>
  <strong>Hc err:</strong>
  <%= @opportunity._hc_err %>
</p>

<p>
  <strong>Type:</strong>
  <%= @opportunity.type %>
</p>

<p>
  <strong>Sfid:</strong>
  <%= @opportunity.sfid %>
</p>

<p>
  <strong>Natureofwork  c:</strong>
  <%= @opportunity.natureofwork__c %>
</p>

<p>
  <strong>Pursuitteam  c:</strong>
  <%= @opportunity.pursuitteam__c %>
</p>

<p>
  <strong>Createddate:</strong>
  <%= @opportunity.createddate %>
</p>

<p>
  <strong>Name:</strong>
  <%= @opportunity.name %>
</p>

<%= link_to 'Edit', edit_opportunity_path(@opportunity) %> |
<%= link_to 'Back', opportunities_path %>