config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :opportunities
  resources :post_tests
  resources :entries
  resources :contacts
  get 'welcome/index'

  root 'welcome#index'

end

app/models/account.rb
class Account < SalesforceModel
  #self.table_name = ENV['HEROKUCONNECT_SCHEMA'] + '.contact'
  self.table_name = 'account'
  has_many :contacts, :primary_key => 'sfid', :foreign_key => 'accountid'

  #attr_protected :createddate, :systemmodstamp, :lastmodifieddate
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:accountteam__c, :_hc_lastop, :_hc_err, :account_md_d__c, :account_md_d_title__c, :phone, :isdeleted, :account_md_d_email__c, :account_md_d_name__c, :annualrevenue, :recordtypeid, :assets_reported_date__c, :accountmanager__c, :name, :account_manager__c, :systemmodstamp, :account_md_d_phone__c, :accountsitetype__c, :accountsource, :createddate, :website, :sfid)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :accountteam__c %><br>
    <%= f.text_field :accountteam__c %>
  </div>
  <div class="field">
    <%= f.label :_hc_lastop %><br>
    <%= f.text_field :_hc_lastop %>
  </div>
  <div class="field">
    <%= f.label :_hc_err %><br>
    <%= f.text_area :_hc_err %>
  </div>
  <div class="field">
    <%= f.label :account_md_d__c %><br>
    <%= f.text_field :account_md_d__c %>
  </div>
  <div class="field">
    <%= f.label :account_md_d_title__c %><br>
    <%= f.text_field :account_md_d_title__c %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :isdeleted %><br>
    <%= f.check_box :isdeleted %>
  </div>
  <div class="field">
    <%= f.label :account_md_d_email__c %><br>
    <%= f.text_field :account_md_d_email__c %>
  </div>
  <div class="field">
    <%= f.label :account_md_d_name__c %><br>
    <%= f.text_field :account_md_d_name__c %>
  </div>
  <div class="field">
    <%= f.label :annualrevenue %><br>
    <%= f.text_field :annualrevenue %>
  </div>
  <div class="field">
    <%= f.label :recordtypeid %><br>
    <%= f.text_field :recordtypeid %>
  </div>
  <div class="field">
    <%= f.label :assets_reported_date__c %><br>
    <%= f.date_select :assets_reported_date__c %>
  </div>
  <div class="field">
    <%= f.label :accountmanager__c %><br>
    <%= f.text_field :accountmanager__c %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :account_manager__c %><br>
    <%= f.text_field :account_manager__c %>
  </div>
  <div class="field">
    <%= f.label :systemmodstamp %><br>
    <%= f.datetime_select :systemmodstamp %>
  </div>
  <div class="field">
    <%= f.label :account_md_d_phone__c %><br>
    <%= f.text_field :account_md_d_phone__c %>
  </div>
  <div class="field">
    <%= f.label :accountsitetype__c %><br>
    <%= f.text_field :accountsitetype__c %>
  </div>
  <div class="field">
    <%= f.label :accountsource %><br>
    <%= f.text_field :accountsource %>
  </div>
  <div class="field">
    <%= f.label :createddate %><br>
    <%= f.datetime_select :createddate %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :sfid %><br>
    <%= f.text_field :sfid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<style>
  table{
      border-collapse: separate;
    border-spacing: 10px 5px;
  }
</style>


<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Account Team</th>
      <th>Account Title</th>
      <th>Phone</th>
      <th>Account Email</th>
      <th>Account Name</th>
      <th>Annual Revenue</th>
      <th>Name</th>
      <th>Account Phone</th>
      <th>Account Site Type</th>
      <th>Created Date</th>
      <th>Website</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.accountteam__c %></td>
        <td><%= account.account_md_d_title__c %></td>
        <td><%= account.phone %></td>
        <td><%= account.account_md_d_email__c %></td>
        <td><%= account.account_md_d_name__c %></td>
        <td><%= account.annualrevenue %></td>
        <td><%= account.name %></td>
        <td><%= account.account_md_d_phone__c %></td>
        <td><%= account.accountsitetype__c %></td>
        <td><%= account.createddate %></td>
        <td><%= account.website %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accountteam  c:</strong>
  <%= @account.accountteam__c %>
</p>

<p>
  <strong>Hc lastop:</strong>
  <%= @account._hc_lastop %>
</p>

<p>
  <strong>Hc err:</strong>
  <%= @account._hc_err %>
</p>

<p>
  <strong>Account md d  c:</strong>
  <%= @account.account_md_d__c %>
</p>

<p>
  <strong>Account md d title  c:</strong>
  <%= @account.account_md_d_title__c %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @account.phone %>
</p>

<p>
  <strong>Isdeleted:</strong>
  <%= @account.isdeleted %>
</p>

<p>
  <strong>Account md d email  c:</strong>
  <%= @account.account_md_d_email__c %>
</p>

<p>
  <strong>Account md d name  c:</strong>
  <%= @account.account_md_d_name__c %>
</p>

<p>
  <strong>Annualrevenue:</strong>
  <%= @account.annualrevenue %>
</p>

<p>
  <strong>Recordtypeid:</strong>
  <%= @account.recordtypeid %>
</p>

<p>
  <strong>Assets reported date  c:</strong>
  <%= @account.assets_reported_date__c %>
</p>

<p>
  <strong>Accountmanager  c:</strong>
  <%= @account.accountmanager__c %>
</p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Account manager  c:</strong>
  <%= @account.account_manager__c %>
</p>

<p>
  <strong>Systemmodstamp:</strong>
  <%= @account.systemmodstamp %>
</p>

<p>
  <strong>Account md d phone  c:</strong>
  <%= @account.account_md_d_phone__c %>
</p>

<p>
  <strong>Accountsitetype  c:</strong>
  <%= @account.accountsitetype__c %>
</p>

<p>
  <strong>Accountsource:</strong>
  <%= @account.accountsource %>
</p>

<p>
  <strong>Createddate:</strong>
  <%= @account.createddate %>
</p>

<p>
  <strong>Website:</strong>
  <%= @account.website %>
</p>

<p>
  <strong>Sfid:</strong>
  <%= @account.sfid %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>